Fix/eth yield farm
unchain-tech/UNCHAIN-projects pull request #390
Opened 2023-05-28 02:03 UTC by honganji

## 変更内容
- フォークの際にmainブランチを選択するように促す記述を追加
- contractとclientのファイル名が間違っている箇所がいくつかあったので修正
- モノレポ化に伴って説明が重複している部分があったので調整

## 背景
プロジェクトのレポジトリに見本用のブランチも加えたことでフォークの際にブランチを選択する必要が発生したこと。

## 備考

2023-05-28 07:52 UTC, yk-saito commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +その後`packages`ディレクトリに移動します。
不要ですかね？

2023-05-28 07:52 UTC, yk-saito commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +✔ Hardhat project root: · /ETH-dApp/packages/contract
`ETH-dApp`になってしまっています！

2023-05-28 07:52 UTC, yk-saito commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +ETH-dApp
`ETH-dApp`になってしまっています！

2023-05-28 07:52 UTC, yk-saito commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +![](/public/images/ETH-dApp/section-1/1_2_1.png)
`ETH-dApp`

2023-05-29 01:29 UTC, neila approved these changes

2023-05-29 01:30 UTC, neila requested changes

2023-05-29 01:30 UTC, neila commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +![](/public/images/ETH-Yield-Farm/section-2/2_2_1.png)
この辺とか割と無造作に画像ファイルパスが書き換えられているように見えるのですが大丈夫ですか

2023-05-29 04:09 UTC, honganji commented on docs/ETH-Yield-Farm/ja/section-1/lesson-1_環境構築をしよう.md
> +![](/public/images/ETH-Yield-Farm/section-2/2_2_1.png)
大丈夫です、きちんと意図した画像が表示されています。
<img width="1680" alt="SS 2023-05-29 at 13 06 39" src="https://github.com/unchain-tech/UNCHAIN-projects/assets/85441887/0e4377fa-a73a-43e5-bb3e-b5c910fcdfb9">

2023-05-30 00:17 UTC, closed without merging